USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_DATAOPS;
USE DATABASE DATAOPS_COURSE;
USE SCHEMA PROVIDERS;

CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER
    COMMENT = 'Opera el pipeline, necesita el dato crudo para depurar';
CREATE ROLE IF NOT EXISTS ROLE_DATA_ANALYST
    COMMENT = 'Analiza proveedores, necesita contexto parcial, no el contacto completo';
CREATE ROLE IF NOT EXISTS ROLE_BUSINESS_MANAGER
    COMMENT = 'Contacta proveedores, necesita el contacto completo, no el resto del contexto';

GRANT USAGE ON WAREHOUSE WH_DATAOPS TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_DATAOPS TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON WAREHOUSE WH_DATAOPS TO ROLE ROLE_BUSINESS_MANAGER;

GRANT USAGE ON DATABASE DATAOPS_COURSE TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON DATABASE DATAOPS_COURSE TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON DATABASE DATAOPS_COURSE TO ROLE ROLE_BUSINESS_MANAGER;

GRANT USAGE ON SCHEMA PROVIDERS TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON SCHEMA PROVIDERS TO ROLE ROLE_DATA_ANALYST;
GRANT USAGE ON SCHEMA PROVIDERS TO ROLE ROLE_BUSINESS_MANAGER;

GRANT SELECT ON TABLE STG_PROVIDERS_FLATTENED TO ROLE ROLE_DATA_ENGINEER;
GRANT SELECT ON TABLE STG_PROVIDERS_FLATTENED TO ROLE ROLE_DATA_ANALYST;
GRANT SELECT ON TABLE STG_PROVIDERS_FLATTENED TO ROLE ROLE_BUSINESS_MANAGER;

GRANT ROLE ROLE_DATA_ENGINEER    TO USER TMARINA;
GRANT ROLE ROLE_DATA_ANALYST     TO USER TMARINA;
GRANT ROLE ROLE_BUSINESS_MANAGER TO USER TMARINA;

SELECT contact_name, phone FROM STG_PROVIDERS_FLATTENED ORDER BY contact_name;

CREATE OR REPLACE MASKING POLICY mask_phone AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() = 'ROLE_BUSINESS_MANAGER' THEN val
        WHEN CURRENT_ROLE() = 'ROLE_DATA_ANALYST'  THEN CONCAT(LEFT(val, 6), '-****')
        ELSE '***-***-****'
    END;

ALTER TABLE STG_PROVIDERS_FLATTENED MODIFY COLUMN phone SET MASKING POLICY mask_phone;


USE ROLE ROLE_DATA_ENGINEER;
SELECT contact_name, phone FROM STG_PROVIDERS_FLATTENED ORDER BY contact_name;


USE ROLE ROLE_DATA_ANALYST;
SELECT contact_name, phone FROM STG_PROVIDERS_FLATTENED ORDER BY contact_name;

USE ROLE ROLE_BUSINESS_MANAGER;
SELECT contact_name, phone FROM STG_PROVIDERS_FLATTENED ORDER BY contact_name;

USE ROLE ACCOUNTADMIN; 