CREATE WAREHOUSE IF NOT EXISTS WH_DATAOPS
    WAREHOUSE_SIZE      = 'XSMALL'
    AUTO_SUSPEND        = 60
    AUTO_RESUME         = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT             = 'Warehouse del taller mecánico - Equipo 1';

CREATE DATABASE IF NOT EXISTS DATAOPS_COURSE
    COMMENT = 'Data Warehouse del caso de Taller mecánico — Equipo 1';

CREATE SCHEMA IF NOT EXISTS DATAOPS_COURSE.RAW
    COMMENT = 'Landing zone: datos extraídos de Neon, sin transformar';

CREATE ROLE IF NOT EXISTS DATAOPS_LOADER
    COMMENT = 'Rol de servicio para el ELT. Sin privilegios de administración.';

GRANT USAGE ON WAREHOUSE WH_DATAOPS TO ROLE DATAOPS_LOADER;
GRANT USAGE ON DATABASE DATAOPS_COURSE TO ROLE DATAOPS_LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA DATAOPS_COURSE.RAW TO ROLE DATAOPS_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA DATAOPS_COURSE.RAW TO ROLE DATAOPS_LOADER;

GRANT ROLE DATAOPS_LOADER TO USER tmarina;

USE WAREHOUSE WH_DATAOPS;
USE DATABASE DATAOPS_COURSE;
USE SCHEMA RAW;

SHOW WAREHOUSES LIKE 'WH_DATAOPS';
SHOW SCHEMAS IN DATABASE DATAOPS_COURSE;
SHOW GRANTS TO ROLE DATAOPS_LOADER;
